Ajouter Avertissement pour Compiler sur iOS
PapillonApp/DocsDeveloppeur pull request #2
Opened 2024-09-04 17:10 UTC by cleeemeeent

Les 2 1ers commits étaient pour test, je les ai enlevés par la suite

2024-09-04 17:21 UTC, Slysoks commented
Ah ouais ?! c vrmt des rats Apple mais bon, ils sont qd même très forts

2024-09-04 17:25 UTC, cleeemeeent commented
Yep faut en avoir un pour compiler 💀

2024-09-04 20:32 UTC, Louis-htmlcss commented
Dit que tu peux aussi utiliser un pipeline tel que GitHub actions pour build

2024-09-04 20:33 UTC, Louis-htmlcss requested changes
Dit que tu peux aussi utiliser un pipeline tel que GitHub actions pour build

2024-09-04 20:33 UTC, cleeemeeent commented
Hein 💀

2024-09-04 20:34 UTC, cleeemeeent commented
On a dit un truc qui convient aux débutants hein

2024-09-04 20:37 UTC, Louis-htmlcss commented
> On a dit un truc qui convient aux débutants hein

Si un gars a pas un mac il faut qu'il sache ça quand même

2024-09-04 20:38 UTC, cleeemeeent commented
Bah attends je modifie du coup

2024-09-04 20:46 UTC, Clmnnt commented
@Louis-htmlcss ça te va comme ça ?

2024-09-04 20:47 UTC, Louis-htmlcss commented
> @Louis-htmlcss ça te va comme ça ?
> 

Comment ca si vous en avez besoin ptdr

2024-09-04 20:48 UTC, cleeemeeent commented
Ouais mais a l’ancienne doc j’ai jamais vu de pipeline

2024-09-04 20:48 UTC, Louis-htmlcss commented
Un petit lien vers le workflow de yannou ne serait pas de refus ptdr

2024-09-04 20:49 UTC, cleeemeeent commented
Passe le lien?

> Un petit lien vers le workflow de yannou ne serait pas de refus ptdr

2024-09-04 20:50 UTC, Louis-htmlcss commented
> Passe le lien?
> 
> > Un petit lien vers le workflow de yannou ne serait pas de refus ptdr
> 
> 

https://github.com/PapillonApp/Papillon/blob/main/.github/workflows/start_build.yml

2024-09-04 20:54 UTC, cleeemeeent commented
@Louis-htmlcss

2024-09-04 20:55 UTC, Louis-htmlcss commented
Parfait

2024-09-04 20:55 UTC, Orafilynie commented
Vous savez qu’ils faut un certificat apple pour utiliser le workflow ?

2024-09-04 20:55 UTC, Louis-htmlcss approved these changes

2024-09-04 20:55 UTC, cleeemeeent commented
Louis andouille :zjesus:

2024-09-04 20:55 UTC, Louis-htmlcss commented
> Vous savez qu’ils faut un certificat apple pour utiliser le workflow ?
Je sais mais ça fait un peu compliqué

2024-09-04 20:56 UTC, cleeemeeent commented
> > Vous savez qu’ils faut un certificat apple pour utiliser le workflow ?
> > Je sais mais ça fait un peu compliqué

 Bah autant ne pas le mettre ?

2024-09-04 20:59 UTC, Orafilynie commented
Apres tu peut toujours modifier le workflow pour build un artifact non signé mais tu devra le signer par tes propres moyens pour l’installer sur ton appareil

2024-09-04 20:59 UTC, cleeemeeent commented
Je trouve ça trop compliqué pour une doc destiné a tout le monde, y’en a qui vont pas comprendre

2024-09-04 21:00 UTC, Clmnnt commented
J’enlève du coup?

2024-09-04 21:04 UTC, cleeemeeent commented
Louis j’ai fait une connerie j’ai enlevé ton approbation 💀

2024-09-04 21:05 UTC, Louis-htmlcss approved these changes

2024-09-04 22:05 UTC, Louis-htmlcss commented
Je vais sûrement faire une pr pour modif le workflow donc bon

2024-09-05 05:50 UTC, cleeemeeent commented
> Je vais sûrement faire une pr pour modif le workflow donc bon

Bah tu le feras de ton côté

2024-10-06 18:48 UTC, Louis-htmlcss commented
Oublie pas de dire que les fonctionnalités natives ne marchent pas

2024-10-06 19:04 UTC, cleeemeeent commented
att je close celle ci

2024-10-06 19:04 UTC, closed without merging