chore: Update installation and startup commands in demarrage-rapide.md
PapillonApp/DocsDeveloppeur pull request #3
Opened 2024-09-04 17:20 UTC by Slysoks

Amélioration **sans IA** à la PR de Louis

2024-09-04 17:23 UTC, cleeemeeent requested changes
T’as fait une petite faute a « temps réel », sûrement une faute de frappe

2024-09-04 17:33 UTC, Slysoks commented
Bv

2024-09-04 18:42 UTC, cleeemeeent approved these changes
LGTM

2024-09-04 18:43 UTC, cleeemeeent commented
À voir avec Yann si il faut laisser les 3 Warning mais je pense pas

2024-09-04 18:44 UTC, cleeemeeent approved these changes

2024-09-04 18:44 UTC, cleeemeeent commented
J'avais fait une connerie

2024-09-04 18:46 UTC, Slysoks commented
Par contre c qui qui approve ?

2024-09-04 18:47 UTC, cleeemeeent commented
Je crois que c'est @yannouuuu qui peut merge

2024-09-04 18:47 UTC, cleeemeeent commented
Et les autres contribs de Papillon

2024-09-04 19:05 UTC, Slysoks commented
Faut mettre quoi dans les checkbox ?

2024-09-04 19:07 UTC, cleeemeeent commented
> Faut mettre quoi dans les checkbox ?

Peut être un truc du genre 

[x] fonctionnalité 1
[x] fonctionnalité 2
[] fonctionnalité 3 (en dev)

2024-09-04 19:07 UTC, cleeemeeent commented
Bon t’as compris

2024-09-04 19:07 UTC, cleeemeeent commented
Mais chui meme pas sur

2024-09-04 19:17 UTC, yannouuuu commented
Je check après

2024-09-04 20:35 UTC, Louis-htmlcss requested changes
Expo cli est outdated, pas besoin d'installer les dépendances, il faut juste lancé npx expo start

2024-09-04 20:36 UTC, Louis-htmlcss commented
En plus c'est vraiment une copie de ma pr

2024-09-04 20:37 UTC, cleeemeeent commented
@Louis-htmlcss c’est une
> Amélioration **sans IA** à la PR de Louis

2024-09-04 20:37 UTC, cleeemeeent commented
Donc il c’est inspiré

2024-09-04 20:37 UTC, cleeemeeent commented
Logique

2024-09-04 20:38 UTC, Louis-htmlcss commented
> Donc il c’est inspiré
> 

C'est littéralement une copie avec les mêmes erreurs que chatgpt de con a fait a fait sur ma pr

2024-09-04 20:42 UTC, Louis-htmlcss commented
> Expo cli est outdated, pas besoin d'installer les dépendances, il faut juste lancé npx expo start

Déso j'avais pas vu le truc en bas qui donne l'équivalence mais faut quand même l'enlever car c'est outdated

2024-09-04 20:45 UTC, Louis-htmlcss requested changes

2024-09-04 20:45 UTC, Louis-htmlcss commented on commencer-avec-papillon/demarrage-rapide.md
> +Pour les serveurs ou réseaux avec ports non exposés, utilisez l'option `--tunnel` :
Oublie pas de dire d'accepter l'installation de ngrok si c'est deja pas fait

2024-09-04 20:45 UTC, Louis-htmlcss commented on commencer-avec-papillon/demarrage-rapide.md
> +npm run start -- --tunnel
Pk ya 2 fois 2 tirets ? Fix ça moi bebou

2024-09-04 20:45 UTC, Louis-htmlcss commented on commencer-avec-papillon/demarrage-rapide.md
> +- 🔄 Active le rechargement à chaud (hot reload) pour une mise à jour instantanée de l'application lors des modifications du code
Si c'est en mode dev et pas en mode production

2024-09-04 21:16 UTC, Slysoks commented on commencer-avec-papillon/demarrage-rapide.md
> +npm run start -- --tunnel
Avec npm c comme ça mon beowbeow

2024-09-04 21:18 UTC, Slysoks commented on commencer-avec-papillon/demarrage-rapide.md
> +Pour les serveurs ou réseaux avec ports non exposés, utilisez l'option `--tunnel` :
Je fais ça demain car j'ai une vie qui n'attends pas !! (Je rigole, je geek tt les soirs)

2024-09-05 09:08 UTC, Slysoks commented on commencer-avec-papillon/demarrage-rapide.md
> +- 🔄 Active le rechargement à chaud (hot reload) pour une mise à jour instantanée de l'application lors des modifications du code
Quand tu start l'app t tjrs en mode dev

2024-09-05 10:08 UTC, Gabriel29306 commented
Ce que j'ai mis sur Discord fonctionne, à adapter pour une doc:

Pour utiliser Papillon:
- Cloner le repo: `git clone https://github.com/PapillonApp/Papillon.git`
- Installer les dépendances: `npm i`
- Lancer le serveur expo go: `npm start`
- Se connecter à Expo go depuis son téléphone:
  - Android: scanner le QR code avec l'application expo go
  - iOS: scanner le QR code avec l'application caméra.

2024-09-05 13:59 UTC, Louis-htmlcss commented
> Ce que j'ai mis sur Discord fonctionne, à adapter pour une doc:
> 
> 
> Pour utiliser Papillon:
> - Cloner le repo: `git clone https://github.com/PapillonApp/Papillon.git`
> - Installer les dépendances: `npm i`
> - Lancer le serveur expo go: `npm start`
> - Se connecter à Expo go depuis son téléphone:
>   - Android: scanner le QR code avec l'application expo go
>   - iOS: scanner le QR code avec l'application caméra.

Ya juste a lancer npx expo start 💀

2024-09-05 15:45 UTC, Gabriel29306 commented
Faut bien installer les dépendances à un moment

2024-09-05 15:51 UTC, Louis-htmlcss commented
> Faut bien installer les dépendances à un moment

non, juste npx expo start

2024-09-06 19:46 UTC, cleeemeeent commented
> > Faut bien installer les dépendances à un moment
> 
> non, juste npx expo start

personnellement j'installe toujours les dépendances juste pour être sur que ça marche, le but n'est pas que le développeur ait une erreur même si elle est facile à régler, faut que ça soit rapide, voici pourquoi le nom demarrage-rapide  💀

2024-09-06 20:05 UTC, Louis-htmlcss commented
> > > Faut bien installer les dépendances à un moment
> > 
> > non, juste npx expo start
> 
> personnellement j'installe toujours les dépendances juste pour être sur que ça marche, le but n'est pas que le développeur ait une erreur même si elle est facile à régler, faut que ça soit rapide, voici pourquoi le nom demarrage-rapide  💀 

Ça sert littéralement a rien si il utilise que expo

2024-10-06 09:37 UTC, closed without merging

2024-10-06 15:26 UTC, Gabriel29306 requested changes

2024-10-06 15:26 UTC, Gabriel29306 commented on commencer-avec-papillon/demarrage-rapide.md
> +📚 Pour plus d'informations sur Expo CLI, consultez la [documentation officielle](https://docs.expo.dev/workflow/expo-cli/).
Le lien a bougé pour `https://docs.expo.dev/more/expo-cli/` 😉

2024-10-06 15:26 UTC, Gabriel29306 commented on commencer-avec-papillon/demarrage-rapide.md
> +  ```
Il faut utiliser `@expo/cli` en tant que package local. Le package global `expo-cli` est déprécié.

Donc pour la doc, il faut donc utiliser `npx expo ...` mais je vois que c'est ce que tu as fais 👍

2024-10-06 15:26 UTC, Gabriel29306 commented
Je crois que ma review est plus qu'inutile 😂