add iOS compiling instructions
PapillonApp/DocsDeveloppeur pull request #4
Opened 2024-10-01 21:48 UTC by imyanice

2024-10-01 21:51 UTC, cleeemeeent reviewed
Si c'est possible de me rajouter ça au début : ```
{% hint style="danger" %}Pour compiler Papillon pour iOS, vous devez posséder un Mac.{% endhint %}
```
et après c'est tout bon

2024-10-01 21:52 UTC, cleeemeeent commented
et peut être expliquer avec des images

2024-10-03 19:39 UTC, imyanice commented
sure

2024-10-03 19:45 UTC, imyanice commented
done!

2024-10-06 15:20 UTC, yannouuuu commented
mentionne moi qd tout est good!

2024-10-06 16:34 UTC, imyanice commented
@yannouuuu

2024-10-06 16:41 UTC, yannouuuu commented
> @yannouuuu tout est good ^^

Faut prendre en compte mes reviews par contre avant 😭

2024-10-06 17:01 UTC, cleeemeeent commented
> > @yannouuuu tout est good ^^
> 
> 
> 
> Faut prendre en compte mes reviews par contre avant 😭

Elle est pas la la review 😭

2024-10-06 17:01 UTC, cleeemeeent commented
> > @yannouuuu tout est good ^^
> 
> 
> 
> Faut prendre en compte mes reviews par contre avant 😭

Elle est pas la la review 😭

2024-10-06 17:15 UTC, yannouuuu requested changes

2024-10-06 17:15 UTC, yannouuuu commented on commencer-avec-papillon/compiler-papillon/pour-ios.md
> +2. ouvrir `Papillon.xcworkspace` avec xCode (**TRÈS IMPORTANT**),
Ouvrir avec une majuscule :)

2024-10-06 17:15 UTC, yannouuuu commented on commencer-avec-papillon/compiler-papillon/pour-ios.md
> +1. Dans la racine du projet, exécuter `pnpm prebuild`
btw fait comme cette ligne : enlève toutes les autres virgules à chaque fin de 1. 2. 3.

2024-10-06 17:15 UTC, yannouuuu commented on commencer-avec-papillon/compiler-papillon/pour-ios.md
> +3. Changer les teams pour le signing et enlever les app links si vous n'avez pas de compte payant Apple Developer,
les "appS" (avec un s)

2024-10-06 17:15 UTC, yannouuuu commented
Mb sur tel c pas ouf encore moins dans un métro 😭

2024-10-06 20:03 UTC, imyanice commented
@yannouuuu je pense que c'est tout good maintenant :)

2024-10-06 21:57 UTC, yannouuuu commented
# Pour iOS

{% hint style="danger" %}Pour compiler Papillon pour iOS, vous devez posséder un Mac.{% endhint %} 

1. Dans la racine du projet, exécutez `pnpm prebuild`
2. Ouvrez `Papillon.xcworkspace` avec xCode (**TRÈS IMPORTANT**)
3. **Si** vous n'avez pas de compte payant Apple Developer : changez les teams pour le signing et enlever les "Associated Domains"
4. Sélectionnez `Papillon (release)` dans les schemes et dans votre target (physique ou simulateur)
5. Attendez un peu et c'est tout bon!

![CleanShot 2024-10-03 at 21 41 06](https://github.com/user-attachments/assets/97efe4bc-526e-45b4-b44c-eb281c25a4cc)
![CleanShot 2024-10-03 at 21 42 24](https://github.com/user-attachments/assets/7642b6d0-f296-4e49-89ee-a2f7e81ef728)
![CleanShot 2024-10-03 at 21 44 13](https://github.com/user-attachments/assets/04a8df53-b33f-4909-8738-da2fb131e87c)

@imyanice

2024-10-07 06:45 UTC, imyanice commented
> # Pour iOS
> 
> 
> 
> {% hint style="danger" %}Pour compiler Papillon pour iOS, vous devez posséder un Mac.{% endhint %} 
> 
> 
> 
> 1. Dans la racine du projet, exécutez `pnpm prebuild`
> 
> 2. Ouvrez `Papillon.xcworkspace` avec xCode (**TRÈS IMPORTANT**)
> 
> 3. **Si** vous n'avez pas de compte payant Apple Developer : changez les teams pour le signing et enlever les "Associated Domains"
> 
> 4. Sélectionnez `Papillon (release)` dans les schemes et dans votre target (physique ou simulateur)
> 
> 5. Attendez un peu et c'est tout bon!
> 
> 
> 
> ![CleanShot 2024-10-03 at 21 41 06](https://github.com/user-attachments/assets/97efe4bc-526e-45b4-b44c-eb281c25a4cc)
> 
> ![CleanShot 2024-10-03 at 21 42 24](https://github.com/user-attachments/assets/7642b6d0-f296-4e49-89ee-a2f7e81ef728)
> 
> ![CleanShot 2024-10-03 at 21 44 13](https://github.com/user-attachments/assets/04a8df53-b33f-4909-8738-da2fb131e87c)
> 
> 
> 
> @imyanice 

@yannouuuu done

2024-10-09 10:47 UTC, imyanice commented
@yannouuuu

2024-10-09 10:49 UTC, merged